version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
      - VITE_WS_URL=ws://localhost:8001
      - VITE_LIVEKIT_URL=ws://localhost:7880
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - livestream_network
    restart: unless-stopped

networks:
  livestream_network:
    external: true
