version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - livestream_network
    restart: unless-stopped

networks:
  livestream_network:
    external: true
